version: '3'
services:
  thredds:
    image: unidata/thredds-docker:5.6
    container_name: oceanenv-thredds
    ports:
      - "8080:8080"
    volumes:
      - ./thredds-content:/usr/local/tomcat/content/thredds
      - ./data:/data
    restart: unless-stopped
